### ISSUE TITLE
Method not allowed exception on user update with BootstrapCMS

### ISSUE THREAD

**Issue by LucaPon** [BootstrapCMS/Credentials#50]
I saw you use the $router->resource() in your credential module, but when I try to update the user, eg: changing permission, laravel throws me the MethodNotAllowedException.
Running the artisan route:list I saw it accepts the PUT method on users/{users} but the generated form in the credentials/views/edit.blade.php file has the method set as POST. Setting the method to PUT it works well.

**Comment by GrahamCampbell** [comment]
Is your javascript working?

**Comment by LucaPon** [comment]
Yes, nothing is dropped in the console.

**Comment by GrahamCampbell** [comment]
Bootstrap CMS probably doesnt ship with the latest deps. Try updating them.

**Comment by bluefrost** [comment]
I have a very similar issue. Not sure whether I should open a new ticket because this one is closed.

I have fresh install of the Bootstrap CMS from Git installed using composer (so it's up to date). When I go to path **account/profile**  to change admin password and I check the page source, the password change form has method PATCH.

After submitting the new password, I end up on page with url address:
`http://dev.laravel/account/password?_token=mYlvdKzLN7pohexKeAJ0HtupEt9aRdZjACLSzIDR&password=newpassword&password_confirmation=newpassword`

On the page, there is error 405 "Method not allowed".

But when I debug the request in Fiddler, the request is like this:
`GET /account/password?_token=mYlvdKzLN7pohexKeAJ0HtupEt9aRdZjACLSzIDR&password=newpassword&password_confirmation=newpassword HTTP/1.1`

In my opinion, there are two issues here: 

1. the 405 error
2. sending password in plain text over the url

It's possible that I am lacking some configuration, but I have no clue what it could be (I revised all points on the Credentials install readme page and it seems that the installer did everything correct).

Any help would be appreciated
